name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          cd quartz
          npx quartz build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@master
        with:
          branch: gh-pages
          folder: quartz/public
